name: github pages

on:
    push:
        branches:
            - main # Set a branch name to trigger deployment
    schedule:
        # Hours specified in UTC, runs 8am-midnight
        - cron: "0,30 15,16,17,18,19,20,21,22,23,0,1,2,3,4,5,6,7 * * *"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: "20.x"
            - run: yarn install --frozen-lockfile
            - run: yarn lint
            - run: yarn start

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./output
                  force_orphan: true
